project:
  type: website
  output-dir: docs  # For GitHub Pages

website:
  title: "Mallick Hossain"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "CV"
        href: files/HossainCV.pdf
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/mallickhossain/
      - icon: github
        href: https://github.com/emallickhossain
      - icon: google
        href: https://scholar.google.com.my/citations?hl=en&user=22Vq08IAAAAJ
        aria-label: Google Scholar
      - icon: envelope
        href: mailto:your.email@philadelphiafed.org

  page-footer:
    center: "© Mallick Hossain, 2026"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
